FROM node:8.12-slim

# Install tools & libs to compile everything
RUN apt-get update && apt-get install -y \
        build-essential \
        libssl-dev \
        libreadline-dev \
        wget \
        zip \
        python-pip \
        python-dev \
        imagemagick \
        libmagick++-dev \
        libmagic-dev \
         && apt-get clean
RUN pip install awscli --upgrade
ENV PATH=$PATH:~/opt/bin:~/opt/node/bin:/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16

COPY . /visual-droid
WORKDIR /visual-droid
RUN npm install
CMD bash